### ISSUE TITLE
Some bedGraph files were omitted due to low signal

### ISSUE THREAD

**Issue by yztxwd** [guanjue/S3norm#2]
Hi:

I was trying to use S3norm to normalize 100 signal tracks, what I did is first use bigWigAverageOverBed to get the coverage of these tracks over the same bed file, then run s3norm_pipeline.py on it as the example shown in the tutorial.

The pipeline finished without fatal error, but I found there are 4 files missed in the final output folder "S3norm_rc_bedgraph". Then I went back to the log info, it seems several errors happened but they didn't stop the pipeline. I listed things I found here:

1. This is the first error I found, so I guess S3norm requires at least 30 bins with >1 signal?
```
Get S3norm normalized read counts......Done
Get signal track of negative log10 p-value based on a NB background model......
Error in quantile.default(sig, 0.99) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Calls: quantile -> quantile.default
Execution halted
[1] "Bins with signal greater than 1 is Less than 30. There may have some problem in the data"
```

2. Then follows some file not found errors in different ways, it might be due to the previous step didn't generate the expected ouput?
`cut: mES_mC-hmC_fixed_averageOver_low_mnase_h2b_t0.bedGraph.s3norm.NB.neglog10p.bedgraph: No such file or directory
`
```
start S3norm.......
Traceback (most recent call last):
  File "S3norm/src//s3norm.py", line 473, in <module>
    main(sys.argv[1:])
  File "S3norm/src//s3norm.py", line 470, in main
    s3norm(sig1_wg_raw, sig2_wg_raw, sig2_output_name, NTmethod, B_init, fdr_thresh, rank_lim, upperlim, lowerlim, p_method, common_pk_binary, common_bg_binary, cross_mark)
  File "S3norm/src//s3norm.py", line 182, in s3norm
    sig2_raw = read2d_array(sig2_wg_raw, str)
  File "S3norm/src//s3norm.py", line 11, in read2d_array
    data=open(filename,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'mES_mC-hmC_fixed_averageOver_low_mnase_h2b_t0.bedGraph.s3norm.NB.neglog10p.bedgraph'
```
```
mv: cannot stat ‘*.NBP.info.txt’: No such file or directory
mv: cannot stat ‘*.NBP.s3norm.bedgraph’: No such file or directory
```

Btw, two of the omitted files are CpG methylation percentage, which never exceeds 1 at any base pair. These two files might not be appropriate for S3norm, but there are two other very sparse ATAC-seq files omitted, I'm wondering does S3norm have any requirement on the signal strength in input files?

**Comment by guanjue** [comment]
Yes, the S3norm assumes counts data or average counts per bin with read extension. So it usually needs at least several thousands bin (200bp per bin) with signal greater than 1 to work properly.

By the way, the S3norm Ver2 (https://github.com/guanjue/S3V2_IDEAS_ESMP) is the recommended version which has easier input (bigwig file). And S3V2 also has better denoise power.

**Comment by yztxwd** [comment]
> Yes, the S3norm assumes counts data or average counts per bin with read extension. So it usually needs at least several thousands bin (200bp per bin) with signal greater than 1 to work properly.
> 
> By the way, the S3norm Ver2 (https://github.com/guanjue/S3V2_IDEAS_ESMP) is the recommended version which has easier input (bigwig file). And S3V2 also has better denoise power.

Thanks for the reply! I used this repo because I only need the normalized signal, but I just found S3V2 output has a directory containing the normalized files, thanks for bringing this out!
